name: Build for all platforms

on:
  push:
    branches: [master, fix-player-icon-error]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build HTML5
        uses: josephbmanley/build-godot-action@v1.3.3
        with:
          name: UoLGJ-TeamOne
          preset: HTML5
          projectDir: .
          debugMode: true
          subdirectory: 'html5'
      - name: 'Deploy to Netlify'
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build/html5 --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
